#!/usr/bin/env bash
# setup-xinitrc.sh — Generate ~/.xinitrc for the DWM suckless desktop.
# Run as your NORMAL USER (not root) on the target Gentoo box.
#
# What this script does:
#   1. Creates ~/Pictures/wallpaper/ if it doesn't exist
#   2. Copies wallpapers from the repo's wallpaper/ directory
#   3. Generates ~/.xinitrc configured for:
#      - 2560x1440 @ 154.85 Hz (xrandr)
#      - Keyboard repeat: 200ms delay, 35 repeats/sec (xset)
#      - xwallpaper with wall2.png
#      - PipeWire + WirePlumber audio
#      - picom compositor + dunst notifications
#      - slstatus or fallback status bar
#      - dwm as the window manager
#
# Usage:
#   ./scripts/setup-xinitrc.sh
set -euo pipefail

# ── Colour helpers ───────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { printf "${GREEN}>>>${NC} %s\n" "$*"; }
warn()  { printf "${YELLOW}>>>${NC} %s\n" "$*"; }
die()   { printf "${RED}ERROR:${NC} %s\n" "$*" >&2; exit 1; }

# ── Pre-flight checks ───────────────────────────────────────────────
[[ $EUID -ne 0 ]] || die "Run this as your normal user, not root."

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
WALLPAPER_SRC="$REPO_DIR/wallpaper"
WALLPAPER_DEST="$HOME/Pictures/wallpaper"
XINITRC="$HOME/.xinitrc"

# ── Set up wallpaper directory ───────────────────────────────────────
info "Setting up wallpaper directory: $WALLPAPER_DEST"
mkdir -p "$WALLPAPER_DEST"

if [[ -d "$WALLPAPER_SRC" ]] && ls "$WALLPAPER_SRC"/* &>/dev/null; then
    cp -n "$WALLPAPER_SRC"/* "$WALLPAPER_DEST"/
    info "Copied wallpapers from repo → $WALLPAPER_DEST"
    ls -1 "$WALLPAPER_DEST"/
else
    warn "No wallpapers found in $WALLPAPER_SRC — directory created but empty."
fi

# ── Check that wall2.png exists ──────────────────────────────────────
if [[ ! -f "$WALLPAPER_DEST/wall2.png" ]]; then
    warn "wall2.png not found in $WALLPAPER_DEST — xwallpaper will fail at startx."
    warn "Place a wallpaper there or edit ~/.xinitrc to change the filename."
fi

# ── Back up existing .xinitrc ────────────────────────────────────────
if [[ -f "$XINITRC" ]]; then
    BACKUP="${XINITRC}.bak.$(date +%Y%m%d%H%M%S)"
    cp "$XINITRC" "$BACKUP"
    info "Backed up existing .xinitrc → $BACKUP"
fi

# ── Generate .xinitrc ────────────────────────────────────────────────
info "Writing $XINITRC"

cat > "$XINITRC" << 'XINITRC_EOF'
#!/bin/sh
# ~/.xinitrc — generated by setup-xinitrc.sh
# startx reads this file and launches X with these settings.

# ── Display ───────────────────────────────────────
# Safe default — auto-detect connected monitors and set native resolution.
xrandr --auto

# Uncomment the line below for 1440p @ 154.85 Hz once you've confirmed
# your monitor supports it (run 'xrandr' to list available modes):
# xrandr --output "$(xrandr | grep ' connected' | head -1 | awk '{print $1}')" --mode 2560x1440 --rate 154.85

# ── Input ─────────────────────────────────────────
# Keyboard layout — change "us" to your layout (gb, de, fr, etc.).
setxkbmap us

# Keyboard repeat rate: 200ms delay before repeat starts,
# then 35 characters per second. Makes typing feel snappy.
xset r rate 200 35

# ── Wallpaper ─────────────────────────────────────
# xwallpaper sets the root window background image.
# --zoom scales the image to fill the screen (crops if aspect differs).
xwallpaper --zoom ~/Pictures/wallpaper/wall2.png

# ── Audio (PipeWire as user) ──────────────────────
# PipeWire must run as your user (not root). Start in background.
# wireplumber is the session manager (routing, device policy).
pipewire &
wireplumber &

# ── Compositor ────────────────────────────────────
# picom adds vsync (eliminates tearing), transparency, and shadows.
# -b runs it as a background daemon.
picom -b &

# ── Notifications ─────────────────────────────────
# dunst displays desktop notifications sent via D-Bus.
# Configure in ~/.config/dunst/dunstrc.
dunst &

# ── Status bar ────────────────────────────────────
# Use slstatus if installed, otherwise fall back to a simple xsetroot loop.
if command -v slstatus >/dev/null 2>&1; then
    slstatus &
else
    while true; do
        xsetroot -name "$(date '+%a %b %d  %H:%M')  |  $(awk '/MemAvailable/{printf "%.0fM", $2/1024}' /proc/meminfo) free"
        sleep 30
    done &
fi

# ── Window manager ────────────────────────────────
# 'exec' replaces this shell process with dwm.
# When you quit dwm (Mod+Shift+Q), X exits → back to TTY.
exec dwm
XINITRC_EOF

chmod +x "$XINITRC"

# ── Add autostart to ~/.bash_profile (commented out) ─────────────────
BASH_PROFILE="$HOME/.bash_profile"
if ! grep -q 'exec startx' "$BASH_PROFILE" 2>/dev/null; then
    info "Adding autostart block to $BASH_PROFILE (commented out)"
    cat >> "$BASH_PROFILE" << 'AUTOSTART_EOF'

# ── Auto-start X on tty1 (uncomment to enable) ───────────────────────
# Only triggers on tty1 — other TTYs stay as text consoles.
# 'exec startx' replaces the login shell with startx — when X exits,
# you're logged out (back to the login prompt).
# if [[ -z "$DISPLAY" && "$(tty)" == "/dev/tty1" ]]; then
#     exec startx
# fi
AUTOSTART_EOF
else
    info "Autostart block already present in $BASH_PROFILE — skipping."
fi

info "Done! ~/.xinitrc is ready."
info ""
info "Make sure these packages are installed:"
info "  emerge -a x11-apps/xrandr x11-apps/setxkbmap x11-apps/xsetroot"
info "  emerge -a x11-misc/xwallpaper x11-misc/picom x11-misc/dunst"
info "  emerge -a media-video/pipewire media-video/wireplumber"
info ""
info "Start X with: startx"
